### ISSUE TITLE
Using a local LLM

### ISSUE THREAD

**Issue by HAL9KKK** [connery-io/connery#95]
I would like to use a local LLM instead of OpenAI, how to change the .env insert the path for the local LLM?

**Comment by machulav** [comment]
@HAL9KKK Can you please describe your use case in more detail so we can better understand and help you?

The `OPENAI_API_KEY` ENV variable is not required for the runner to work. This variable is only needed for the Natural Language Actions, an experimental feature. For example, for the request specified here: [Identify action using natural language](https://docs.connery.io/docs/runner/quick-start/set-up-runner#identify-action-using-natural-language). For Natural Language Actions, we support only OpenAI at the moment. 

However you may not need to use the Natural Language Actions at all. 
Instead you can pull all the available actions with their metadata using API and let your local model decide which action to run. Then, run the action using API. 

If LangChain supports your local model, you can use [Connery Toolkit](https://docs.connery.io/docs/clients/langchain/toolkit) to identify the actions. See example on Python here: https://python.langchain.com/docs/integrations/toolkits/connery#example-of-using-connery-toolkit.
